version: 2
jobs:
  build:
    docker:
      - image: microsoft-dotnet-framework-sdk

    steps:
      - checkout            
      - run:
          name: install dep
          command: |
            dotnet restore
