version: 2.1

orbs:
  win: circleci/windows@1.0.0
  
jobs:
  build:
#     docker:
#       - image: circleci/windows@1.0.0
    steps:
      - checkout            
      - run:
          name: install dep
          command: |
            dotnet build
