executors:
  dotnet2_2:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:2.2'
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build:
    executor: dotnet2_2
    steps:
      - nuget_cache/nuget_restore_cache:
          cache_key: test_save_cache
          project: nuget-cache-orb
      - run: dotnet build
version: 2.1
