executors:
  dotnet2_2:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:2.2'
    working_directory: ~/example-nuget-circle
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build:
    executor: dotnet2_2
    steps:
      - run: dotnet build VulnerableDotNet.sln
version: 2.1
