version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/framework/sdk:4.8

    steps:
      - checkout            
      - run:
          name: install dep
          command: |
            dotnet restore
