version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet-framework:4.7

    steps:
      - checkout            
      - run:
          name: install dep
          command: |
            dotnet restore
